# Generated by Django 4.2.2 on 2023-07-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admincontact/images/')),
            ],
            options={
                'verbose_name': 'Администрация и их контакты',
                'verbose_name_plural': 'Адмистрация и их контакты',
            },
        ),
        migrations.CreateModel(
            name='Deputies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='deputies/images/')),
                ('contact_info', models.TextField()),
            ],
            options={
                'verbose_name': 'Сельские депутаты и их информация',
                'verbose_name_plural': 'Сельские депутаты и их информация',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='history/images/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'История села',
                'verbose_name_plural': 'История села',
            },
        ),
    ]
