<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-07-14 23:01

from django.db import migrations, models
=======
# Generated by Django 4.2.2 on 2023-07-14 05:45

from django.db import migrations
>>>>>>> a9cc3a8556e921f9f9defe921c35d8e4a7fa97c8


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continfo',
            options={'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактная информация'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='massage',
            new_name='message',
        ),
<<<<<<< HEAD
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(default=99675545454, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
=======
>>>>>>> a9cc3a8556e921f9f9defe921c35d8e4a7fa97c8
    ]
