from django.db import migrations, models
# Generated by Django 4.2.2 on 2023-07-14 05:45




class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continfo',
            options={'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактная информация'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='massage',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),

    ]
