# Generated by Django 4.2.2 on 2023-07-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0002_alter_continfo_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(default=56565666666, max_length=20),
            preserve_default=False,
        ),
    ]
